name: Swap functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_functional_tests:
    # This CI job will only trigger on app-boilerplate by default.
    # If you want to keep the SWAP functionality on your application after the fork from
    # boilerplate, you need to remove the 'if' condition to enable the CI to run.
    if: github.repository == 'LedgerHQ/app-boilerplate'
    uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@y333/swap_support_bol
    with:
      branch_for_exchange: 'y333/swap_support_bol'
      branch_for_bol: ${{ github.ref }}
      test_filter: '"boilerplate"'
