name: Swap functional tests

on:
  workflow_dispatch:
  push:
      branches:
        - master
        - main
        - develop
  pull_request:
  
jobs:
    job_functional_tests:
      uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@y333/swap_support_bol
      with:
        branch_for_exchange: 'y333/swap_support_bol'
        branch_for_bol: ${{ github.ref }}
        test_filter: '"boilerplate"'